services:
  api: &main_app
    image: ${IMAGE_URI}
    labels:
      - traefik.enable=true
      - traefik.http.routers.courses_service.rule=Host(`${PRODUCT_CATALOG_TRAEFIK_HOST:-courses_service.localhost}`) || PathPrefix(`/courses-service`)
      - traefik.http.routers.courses_service.entrypoints=web
      - traefik.http.routers.courses_service.service=courses_service
      - traefik.http.services.courses_service.loadbalancer.server.port=${COURSES_SERVICE_PORT:-3000}
      - traefik.http.middlewares.courses_service_strip.stripPrefix.prefixes=/courses-service
      - traefik.http.routers.courses_service.middlewares=courses_service_strip
    networks:
      - traefik-shared
    depends_on:
      - mysql
    ports:
      - "5555:5555"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mydb
      DATABASE_URL: mysql://root:password@mysql:3306/mydb
      ENVIRONMENT: production
      SECRET_KEY:
      OPENAI_API_KEY:
      DD_AGENT_HOST: datadog
      DD_SERVICE: courses-service
      DD_ENV: prod
      DD_LOGS_INJECTION: true
      DD_GIT_REPOSITORY_URL: github.com/classconnect-grupo02/courses-service
      DD_TRACE_SAMPLE_RATE: "1"
      DD_PROFILING_ENABLED: true
      DD_APPSEC_ENABLED: true
      DD_IAST_ENABLED: true
      DD_APPSEC_SCA_ENABLED: true

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - traefik-shared

volumes:
  mysql_data:

networks:
  traefik-shared:
    external: true
