version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: cursos-db-test
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: cursos_test
    ports:
      - "3308:3306" # puerto externo diferente del de dev
    networks:
      - test-network
    volumes:
      - mysql_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  test-network:
    driver: bridge

volumes:
  mysql_test_data:
