name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: 'test-api-key'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # ¡CAMBIO AQUÍ! Usar el nombre del servicio de Docker Compose como host
      DATABASE_URL: "mysql://root:testpassword@mysql-test:3306/cursos_test" 

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Ejecutar tests con preparación y limpieza (Setup, Migrate, Seed, Run)
        # Este único comando ahora inicia DB, espera, migra, hace seed y corre tests.
        # No hace el teardown, lo que permite que Codecov se ejecute después.
        run: npm test -- --coverage --coverageThreshold='{}'

      - name: Subir cobertura a Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: always()

      - name: Apagar Docker Compose para tests
        if: always()
        run: npm run test:teardown